package com.xiongyingqi.java8.stream;

import org.junit.Assert;
import org.junit.Test;

import java.util.HashMap;
import java.util.Map;

/**
 * @author <a href="http://xiongyingqi.com">qi</a>
 * @version 2015-09-28 11:22
 */
public class WordCountTest {
    public static final String WORDS = "User guide for 5.x\n"
            + "Did you know this page is automatically generated from a Github Wiki page? You can improve it by yourself here!\n"
            + "3rd-party translations\n"
            + "Simplified Chinese\n"
            + "Preface\n"
            + "The Problem\n"
            + "Nowadays we use general purpose applications or libraries to communicate with each other. For example, we often use an HTTP client library to retrieve information from a web server and to invoke a remote procedure call via web services.\n"
            + "\n"
            + "However, a general purpose protocol or its implementation sometimes does not scale very well. It is like we don't use a general purpose HTTP server to exchange huge files, e-mail messages, and near-realtime messages such as financial information and multiplayer game data. What's required is a highly optimized protocol implementation which is dedicated to a special purpose. For example, you might want to implement an HTTP server which is optimized for AJAX-based chat application, media streaming, or large file transfer. You could even want to design and implement a whole new protocol which is precisely tailored to your need.\n"
            + "\n"
            + "Another inevitable case is when you have to deal with a legacy proprietary protocol to ensure the interoperability with an old system. What matters in this case is how quickly we can implement that protocol while not sacrificing the stability and performance of the resulting application.\n"
            + "\n"
            + "The Solution\n"
            + "The Netty project is an effort to provide an asynchronous event-driven network application framework and tooling for the rapid development of maintainable high-performance · high-scalability protocol servers and clients.\n"
            + "\n"
            + "In other words, Netty is a NIO client server framework which enables quick and easy development of network applications such as protocol servers and clients. It greatly simplifies and streamlines network programming such as TCP and UDP socket server development.\n"
            + "\n"
            + "'Quick and easy' does not mean that a resulting application will suffer from a maintainability or a performance issue. Netty has been designed carefully with the experiences earned from the implementation of a lot of protocols such as FTP, SMTP, HTTP, and various binary and text-based legacy protocols. As a result, Netty has succeeded to find a way to achieve ease of development, performance, stability, and flexibility without a compromise.\n"
            + "\n"
            + "Some users might already have found other network application framework that claims to have the same advantage, and you might want to ask what makes Netty so different from them. The answer is the philosophy where it is built on. Netty is designed to give you the most comfortable experience both in terms of the API and the implementation from the day one. It is not something tangible but you will realize that this philosophy will make your life much easier as you read this guide and play with Netty.\n"
            + "\n"
            + "Getting Started\n"
            + "This chapter tours around the core constructs of Netty with simple examples to let you get started quickly. You will be able to write a client and a server on top of Netty right away when you are at the end of this chapter.\n"
            + "\n"
            + "If you prefer top-down approach in learning something, you might want to start from Chapter 2, Architectural Overview and get back here.\n"
            + "\n"
            + "Before Getting Started\n"
            + "The minimum requirements to run the examples which are introduced in this chapter are only two; the latest version of Netty and JDK 1.6 or above. The latest version of Netty is available in the project download page. To download the right version of JDK, please refer to your preferred JDK vendor's web site.\n"
            + "\n"
            + "As you read, you might have more questions about the classes introduced in this chapter. Please refer to the API reference whenever you want to know more about them. All class names in this document are linked to the online API reference for your convenience. Also, please don't hesitate to contact the Netty project community and let us know if there's any incorrect information, errors in grammar and typo, and if you have a good idea to improve the documentation.\n"
            + "\n"
            + "Writing a Discard Server\n"
            + "The most simplistic protocol in the world is not 'Hello, World!' but DISCARD. It's a protocol which discards any received data without any response.\n"
            + "\n"
            + "To implement the DISCARD protocol, the only thing you need to do is to ignore all received data. Let us start straight from the handler implementation, which handles I/O events generated by Netty.\n"
            + "\n"
            + "package io.netty.example.discard;\n"
            + "\n"
            + "import io.netty.buffer.ByteBuf;\n"
            + "\n"
            + "import io.netty.channel.ChannelHandlerContext;\n"
            + "import io.netty.channel.ChannelHandlerAdapter;\n"
            + "\n"
            + "/**\n"
            + " * Handles a server-side channel.\n"
            + " */\n"
            + "public class DiscardServerHandler extends ChannelHandlerAdapter { // (1)\n"
            + "\n"
            + "    @Override\n"
            + "    public void channelRead(ChannelHandlerContext ctx, Object msg) { // (2)\n"
            + "        // Discard the received data silently.\n"
            + "        ((ByteBuf) msg).release(); // (3)\n"
            + "    }\n"
            + "\n"
            + "    @Override\n"
            + "    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) { // (4)\n"
            + "        // Close the connection when an exception is raised.\n"
            + "        cause.printStackTrace();\n"
            + "        ctx.close();\n"
            + "    }\n"
            + "}\n"
            + "DiscardServerHandler extends ChannelHandlerAdapter, which is an implementation of ChannelHandler. ChannelHandler provides various event handler methods that you can override. For now, it is just enough to extend ChannelHandlerAdapter rather than to implement the handler interface by yourself.\n"
            + "We override the channelRead() event handler method here. This method is called with the received message, whenever new data is received from a client. In this example, the type of the received message is ByteBuf.\n"
            + "To implement the DISCARD protocol, the handler has to ignore the received message. ByteBuf is a reference-counted object which has to be released explicitly via the release() method. Please keep in mind that it is the handler's responsibility to release any reference-counted object passed to the handler. Usually, channelRead() handler method is implemented like the following:\n"
            + "\n"
            + "@Override\n"
            + "public void channelRead(ChannelHandlerContext ctx, Object msg) {\n"
            + "    try {\n"
            + "        // Do something with msg\n"
            + "    } finally {\n"
            + "        ReferenceCountUtil.release(msg);\n"
            + "    }\n"
            + "}\n"
            + "The exceptionCaught() event handler method is called with a Throwable when an exception was raised by Netty due to an I/O error or by a handler implementation due to the exception thrown while processing events. In most cases, the caught exception should be logged and its associated channel should be closed here, although the implementation of this method can be different depending on what you want to do to deal with an exceptional situation. For example, you might want to send a response message with an error code before closing the connection.\n"
            + "\n"
            + "So far so good. We have implemented the first half of the DISCARD server. What's left now is to write the main() method which starts the server with the DiscardServerHandler.\n"
            + "\n"
            + "package io.netty.example.discard;\n"
            + "\n"
            + "import io.netty.bootstrap.ServerBootstrap;\n"
            + "\n"
            + "import io.netty.channel.ChannelFuture;\n"
            + "import io.netty.channel.ChannelInitializer;\n"
            + "import io.netty.channel.ChannelOption;\n"
            + "import io.netty.channel.EventLoopGroup;\n"
            + "import io.netty.channel.nio.NioEventLoopGroup;\n"
            + "import io.netty.channel.socket.SocketChannel;\n"
            + "import io.netty.channel.socket.nio.NioServerSocketChannel;\n"
            + "\n"
            + "/**\n"
            + " * Discards any incoming data.\n"
            + " */\n"
            + "public class DiscardServer {\n"
            + "\n"
            + "    private int port;\n"
            + "\n"
            + "    public DiscardServer(int port) {\n"
            + "        this.port = port;\n"
            + "    }\n"
            + "\n"
            + "    public void run() throws Exception {\n"
            + "        EventLoopGroup bossGroup = new NioEventLoopGroup(); // (1)\n"
            + "        EventLoopGroup workerGroup = new NioEventLoopGroup();\n"
            + "        try {\n"
            + "            ServerBootstrap b = new ServerBootstrap(); // (2)\n"
            + "            b.group(bossGroup, workerGroup)\n"
            + "             .channel(NioServerSocketChannel.class) // (3)\n"
            + "             .childHandler(new ChannelInitializer<SocketChannel>() { // (4)\n"
            + "                 @Override\n"
            + "                 public void initChannel(SocketChannel ch) throws Exception {\n"
            + "                     ch.pipeline().addLast(new DiscardServerHandler());\n"
            + "                 }\n"
            + "             })\n"
            + "             .option(ChannelOption.SO_BACKLOG, 128)          // (5)\n"
            + "             .childOption(ChannelOption.SO_KEEPALIVE, true); // (6)\n"
            + "\n"
            + "            // Bind and start to accept incoming connections.\n"
            + "            ChannelFuture f = b.bind(port).sync(); // (7)\n"
            + "\n"
            + "            // Wait until the server socket is closed.\n"
            + "            // In this example, this does not happen, but you can do that to gracefully\n"
            + "            // shut down your server.\n"
            + "            f.channel().closeFuture().sync();\n"
            + "        } finally {\n"
            + "            workerGroup.shutdownGracefully();\n"
            + "            bossGroup.shutdownGracefully();\n"
            + "        }\n"
            + "    }\n"
            + "\n"
            + "    public static void main(String[] args) throws Exception {\n"
            + "        int port;\n"
            + "        if (args.length > 0) {\n"
            + "            port = Integer.parseInt(args[0]);\n"
            + "        } else {\n"
            + "            port = 8080;\n"
            + "        }\n"
            + "        new DiscardServer(port).run();\n"
            + "    }\n"
            + "}\n"
            + "NioEventLoopGroup is a multithreaded event loop that handles I/O operation. Netty provides various EventLoopGroup implementations for different kind of transports. We are implementing a server-side application in this example, and therefore two NioEventLoopGroup will be used. The first one, often called 'boss', accepts an incoming connection. The second one, often called 'worker', handles the traffic of the accepted connection once the boss accepts the connection and registers the accepted connection to the worker. How many Threads are used and how they are mapped to the created Channels depends on the EventLoopGroup implementation and may be even configurable via a constructor.\n"
            + "ServerBootstrap is a helper class that sets up a server. You can set up the server using a Channel directly. However, please note that this is a tedious process, and you do not need to do that in most cases.\n"
            + "Here, we specify to use the NioServerSocketChannel class which is used to instantiate a new Channel to accept incoming connections.\n"
            + "The handler specified here will always be evaluated by a newly accepted Channel. The ChannelInitializer is a special handler that is purposed to help a user configure a new Channel. It is most likely that you want to configure the ChannelPipeline of the new Channel by adding some handlers such as DiscardServerHandler to implement your network application. As the application gets complicated, it is likely that you will add more handlers to the pipeline and extract this anonymous class into a top level class eventually.\n"
            + "You can also set the parameters which are specific to the Channel implementation. We are writing a TCP/IP server, so we are allowed to set the socket options such as tcpNoDelay and keepAlive. Please refer to the apidocs of ChannelOption and the specific ChannelConfig implementations to get an overview about the supported ChannelOptions.\n"
            + "Did you notice option() and childOption()? option() is for the NioServerSocketChannel that accepts incoming connections. childOption() is for the Channels accepted by the parent ServerChannel, which is NioServerSocketChannel in this case.\n"
            + "We are ready to go now. What's left is to bind to the port and to start the server. Here, we bind to the port 8080 of all NICs (network interface cards) in the machine. You can now call the bind() method as many times as you want (with different bind addresses.)\n"
            + "Congratulations! You've just finished your first server on top of Netty.\n"
            + "\n"
            + "Looking into the Received Data\n"
            + "Now that we have written our first server, we need to test if it really works. The easiest way to test it is to use the telnet command. For example, you could enter telnet localhost 8080 in the command line and type something.\n"
            + "\n"
            + "However, can we say that the server is working fine? We cannot really know that because it is a discard server. You will not get any response at all. To prove it is really working, let us modify the server to print what it has received.\n"
            + "\n"
            + "We already know that channelRead() method is invoked whenever data is received. Let us put some code into the channelRead() method of the DiscardServerHandler:\n"
            + "\n"
            + "@Override\n"
            + "public void channelRead(ChannelHandlerContext ctx, Object msg) {\n"
            + "    ByteBuf in = (ByteBuf) msg;\n"
            + "    try {\n"
            + "        while (in.isReadable()) { // (1)\n"
            + "            System.out.print((char) in.readByte());\n"
            + "            System.out.flush();\n"
            + "        }\n"
            + "    } finally {\n"
            + "        ReferenceCountUtil.release(msg); // (2)\n"
            + "    }\n"
            + "}\n"
            + "This inefficient loop can actually be simplified to: System.out.println(in.toString(io.netty.util.CharsetUtil.US_ASCII))\n"
            + "Alternatively, you could do in.release() here.\n"
            + "If you run the telnet command again, you will see the server prints what has received.\n"
            + "\n"
            + "The full source code of the discard server is located in the io.netty.example.discard package of the distribution.\n"
            + "\n"
            + "Writing an Echo Server\n"
            + "So far, we have been consuming data without responding at all. A server, however, is usually supposed to respond to a request. Let us learn how to write a response message to a client by implementing the ECHO protocol, where any received data is sent back.\n"
            + "\n"
            + "The only difference from the discard server we have implemented in the previous sections is that it sends the received data back instead of printing the received data out to the console. Therefore, it is enough again to modify the channelRead() method:\n"
            + "\n"
            + "    @Override\n"
            + "    public void channelRead(ChannelHandlerContext ctx, Object msg) {\n"
            + "        ctx.write(msg); // (1)\n"
            + "        ctx.flush(); // (2)\n"
            + "    }\n"
            + "A ChannelHandlerContext object provides various operations that enable you to trigger various I/O events and operations. Here, we invoke write(Object) to write the received message in verbatim. Please note that we did not release the received message unlike we did in the DISCARD example. It is because Netty releases it for you when it is written out to the wire.\n"
            + "ctx.write(Object) does not make the message written out to the wire. It is buffered internally, and then flushed out to the wire by ctx.flush(). Alternatively, you could call ctx.writeAndFlush(msg) for brevity.\n"
            + "If you run the telnet command again, you will see the server sends back whatever you have sent to it.\n"
            + "\n"
            + "The full source code of the echo server is located in the io.netty.example.echo package of the distribution.\n"
            + "\n"
            + "Writing a Time Server\n"
            + "The protocol to implement in this section is the TIME protocol. It is different from the previous examples in that it sends a message, which contains a 32-bit integer, without receiving any requests and loses the connection once the message is sent. In this example, you will learn how to construct and send a message, and to close the connection on completion.\n"
            + "\n"
            + "Because we are going to ignore any received data but to send a message as soon as a connection is established, we cannot use the channelRead() method this time. Instead, we should override the channelActive() method. The following is the implementation:\n"
            + "\n"
            + "package io.netty.example.time;\n"
            + "\n"
            + "public class TimeServerHandler extends ChannelHandlerAdapter {\n"
            + "\n"
            + "    @Override\n"
            + "    public void channelActive(final ChannelHandlerContext ctx) { // (1)\n"
            + "        final ByteBuf time = ctx.alloc().buffer(4); // (2)\n"
            + "        time.writeInt((int) (System.currentTimeMillis() / 1000L + 2208988800L));\n"
            + "\n"
            + "        final ChannelFuture f = ctx.writeAndFlush(time); // (3)\n"
            + "        f.addListener(new ChannelFutureListener() {\n"
            + "\n"
            + "            public void operationComplete(ChannelFuture future) {\n"
            + "                assert f == future;\n"
            + "                ctx.close();\n"
            + "            }\n"
            + "        }); // (4)\n"
            + "    }\n"
            + "\n"
            + "    @Override\n"
            + "    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {\n"
            + "        cause.printStackTrace();\n"
            + "        ctx.close();\n"
            + "    }\n"
            + "}\n"
            + "As explained, the channelActive() method will be invoked when a connection is established and ready to generate traffic. Let's write a 32-bit integer that represents the current time in this method.\n"
            + "To send a new message, we need to allocate a new buffer which will contain the message. We are going to write a 32-bit integer, and therefore we need a ByteBuf whose capacity is at least 4 bytes. Get the current ByteBufAllocator via ChannelHandlerContext.alloc() and allocate a new buffer.\n"
            + "As usual, we write the constructed message.\n"
            + "\n"
            + "But wait, where's the flip? Didn't we used to call java.nio.ByteBuffer.flip() before sending a message in NIO? ByteBuf does not have such a method because it has two pointers; one for read operations and the other for write operations. The writer index increases when you write something to a ByteBuf while the reader index does not change. The reader index and the writer index represents where the message starts and ends respectively.\n"
            + "\n"
            + "In contrast, NIO buffer does not provide a clean way to figure out where the message content starts and ends without calling the flip method. You will be in trouble when you forget to flip the buffer because nothing or incorrect data will be sent. Such an error does not happen in Netty because we have different pointer for different operation types. You will find it makes your life much easier as you get used to it -- a life without flipping out!\n"
            + "\n"
            + "Another point to note is that the ChannelHandlerContext.write() (and writeAndFlush()) method returns a ChannelFuture. A ChannelFuture represents an I/O operation which has not yet occurred. It means, any requested operation might not have been performed yet because all operations are asynchronous in Netty. For example, the following code might close the connection even before a message is sent:\n"
            + "\n"
            + "Channel ch = ...;\n"
            + "ch.writeAndFlush(message);\n"
            + "ch.close();\n"
            + "Therefore, you need to call the close() method after the ChannelFuture is complete, which was returned by the write() method, and it notifies its listeners when the write operation has been done. Please note that, close() also might not close the connection immediately, and it returns a ChannelFuture.\n"
            + "\n"
            + "How do we get notified when a write request is finished then? This is as simple as adding a ChannelFutureListener to the returned ChannelFuture. Here, we created a new anonymous ChannelFutureListener which closes the Channel when the operation is done.\n"
            + "\n"
            + "Alternatively, you could simplify the code using a pre-defined listener:\n"
            + "\n"
            + "f.addListener(ChannelFutureListener.CLOSE);\n"
            + "To test if our time server works as expected, you can use the UNIX rdate command:\n"
            + "\n"
            + "$ rdate -o <port> -p <host>\n"
            + "where <port> is the port number you specified in the main() method and <host> is usually localhost.\n"
            + "\n"
            + "Writing a Time Client\n"
            + "Unlike DISCARD and ECHO servers, we need a client for the TIME protocol because a human cannot translate a 32-bit binary data into a date on a calendar. In this section, we discuss how to make sure the server works correctly and learn how to write a client with Netty.\n"
            + "\n"
            + "The biggest and only difference between a server and a client in Netty is that different Bootstrap and Channel implementations are used. Please take a look at the following code:\n"
            + "\n"
            + "package io.netty.example.time;\n"
            + "\n"
            + "public class TimeClient {\n"
            + "    public static void main(String[] args) throws Exception {\n"
            + "        String host = args[0];\n"
            + "        int port = Integer.parseInt(args[1]);\n"
            + "        EventLoopGroup workerGroup = new NioEventLoopGroup();\n"
            + "\n"
            + "        try {\n"
            + "            Bootstrap b = new Bootstrap(); // (1)\n"
            + "            b.group(workerGroup); // (2)\n"
            + "            b.channel(NioSocketChannel.class); // (3)\n"
            + "            b.option(ChannelOption.SO_KEEPALIVE, true); // (4)\n"
            + "            b.handler(new ChannelInitializer<SocketChannel>() {\n"
            + "                @Override\n"
            + "                public void initChannel(SocketChannel ch) throws Exception {\n"
            + "                    ch.pipeline().addLast(new TimeClientHandler());\n"
            + "                }\n"
            + "            });\n"
            + "\n"
            + "            // Start the client.\n"
            + "            ChannelFuture f = b.connect(host, port).sync(); // (5)\n"
            + "\n"
            + "            // Wait until the connection is closed.\n"
            + "            f.channel().closeFuture().sync();\n"
            + "        } finally {\n"
            + "            workerGroup.shutdownGracefully();\n"
            + "        }\n"
            + "    }\n"
            + "}\n"
            + "Bootstrap is similar to ServerBootstrap except that it's for non-server channels such as a client-side or connectionless channel.\n"
            + "If you specify only one EventLoopGroup, it will be used both as a boss group and as a worker group. The boss worker is not used for the client side though.\n"
            + "Instead of NioServerSocketChannel, NioSocketChannel is being used to create a client-side Channel.\n"
            + "Note that we do not use childOption() here unlike we did with ServerBootstrap because the client-side SocketChannel does not have a parent.\n"
            + "We should call the connect() method instead of the bind() method.\n"
            + "As you can see, it is not really different from the the server-side code. What about the ChannelHandler implementation? It should receive a 32-bit integer from the server, translate it into a human readable format, print the translated time, and close the connection:\n"
            + "\n"
            + "package io.netty.example.time;\n"
            + "\n"
            + "import java.util.Date;\n"
            + "\n"
            + "public class TimeClientHandler extends ChannelHandlerAdapter {\n"
            + "    @Override\n"
            + "    public void channelRead(ChannelHandlerContext ctx, Object msg) {\n"
            + "        ByteBuf m = (ByteBuf) msg; // (1)\n"
            + "        try {\n"
            + "            long currentTimeMillis = (m.readUnsignedInt() - 2208988800L) * 1000L;\n"
            + "            System.out.println(new Date(currentTimeMillis));\n"
            + "            ctx.close();\n"
            + "        } finally {\n"
            + "            m.release();\n"
            + "        }\n"
            + "    }\n"
            + "\n"
            + "    @Override\n"
            + "    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {\n"
            + "        cause.printStackTrace();\n"
            + "        ctx.close();\n"
            + "    }\n"
            + "}\n"
            + "In TCP/IP, Netty reads the data sent from a peer into a `ByteBuf`.\n"
            + "It looks very simple and does not look any different from the server side example. However, this handler sometimes will refuse to work raising an IndexOutOfBoundsException. We discuss why this happens in the next section.\n"
            + "\n"
            + "Dealing with a Stream-based Transport\n"
            + "One Small Caveat of Socket Buffer\n"
            + "\n"
            + "In a stream-based transport such as TCP/IP, received data is stored into a socket receive buffer. Unfortunately, the buffer of a stream-based transport is not a queue of packets but a queue of bytes. It means, even if you sent two messages as two independent packets, an operating system will not treat them as two messages but as just a bunch of bytes. Therefore, there is no guarantee that what you read is exactly what your remote peer wrote. For example, let us assume that the TCP/IP stack of an operating system has received three packets:\n"
            + "\n"
            + "Three packets received as they were sent\n"
            + "\n"
            + "Because of this general property of a stream-based protocol, there's high chance of reading them in the following fragmented form in your application:\n"
            + "\n"
            + "Three packets split and merged into four buffers\n"
            + "\n"
            + "Therefore, a receiving part, regardless it is server-side or client-side, should defrag the received data into one or more meaningful frames that could be easily understood by the application logic. In case of the example above, the received data should be framed like the following:\n"
            + "\n"
            + "Four buffers defragged into three\n"
            + "\n"
            + "The First Solution\n"
            + "\n"
            + "Now let us get back to the TIME client example. We have the same problem here. A 32-bit integer is a very small amount of data, and it is not likely to be fragmented often. However, the problem is that it can be fragmented, and the possibility of fragmentation will increase as the traffic increases.\n"
            + "\n"
            + "The simplistic solution is to create an internal cumulative buffer and wait until all 4 bytes are received into the internal buffer. The following is the modified TimeClientHandler implementation that fixes the problem:\n"
            + "\n"
            + "package io.netty.example.time;\n"
            + "\n"
            + "import java.util.Date;\n"
            + "\n"
            + "public class TimeClientHandler extends ChannelHandlerAdapter {\n"
            + "    private ByteBuf buf;\n"
            + "\n"
            + "    @Override\n"
            + "    public void handlerAdded(ChannelHandlerContext ctx) {\n"
            + "        buf = ctx.alloc().buffer(4); // (1)\n"
            + "    }\n"
            + "\n"
            + "    @Override\n"
            + "    public void handlerRemoved(ChannelHandlerContext ctx) {\n"
            + "        buf.release(); // (1)\n"
            + "        buf = null;\n"
            + "    }\n"
            + "\n"
            + "    @Override\n"
            + "    public void channelRead(ChannelHandlerContext ctx, Object msg) {\n"
            + "        ByteBuf m = (ByteBuf) msg;\n"
            + "        buf.writeBytes(m); // (2)\n"
            + "        m.release();\n"
            + "\n"
            + "        if (buf.readableBytes() >= 4) { // (3)\n"
            + "            long currentTimeMillis = (buf.readUnsignedInt() - 2208988800L) * 1000L;\n"
            + "            System.out.println(new Date(currentTimeMillis));\n"
            + "            ctx.close();\n"
            + "        }\n"
            + "    }\n"
            + "\n"
            + "    @Override\n"
            + "    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {\n"
            + "        cause.printStackTrace();\n"
            + "        ctx.close();\n"
            + "    }\n"
            + "}\n"
            + "A ChannelHandler has two life cycle listener methods: handlerAdded() and handlerRemoved(). You can perform an arbitrary (de)initialization task as long as it does not block for a long time.\n"
            + "First, all received data should be cumulated into buf.\n"
            + "And then, the handler must check if buf has enough data, 4 bytes in this example, and proceed to the actual business logic. Otherwise, Netty will call the channelRead() method again when more data arrives, and eventually all 4 bytes will be cumulated.\n"
            + "The Second Solution\n"
            + "\n"
            + "Although the first solution has resolved the problem with the TIME client, the modified handler does not look that clean. Imagine a more complicated protocol which is composed of multiple fields such as a variable length field. Your ChannelHandler implementation will become unmaintainable very quickly.\n"
            + "\n"
            + "As you may have noticed, you can add more than one ChannelHandler to a ChannelPipeline, and therefore, you can split one monolithic ChannelHandler into multiple modular ones to reduce the complexity of your application. For example, you could split TimeClientHandler into two handlers:\n"
            + "\n"
            + "TimeDecoder which deals with the fragmentation issue, and\n"
            + "the initial simple version of TimeClientHandler.\n"
            + "Fortunately, Netty provides an extensible class which helps you write the first one out of the box:\n"
            + "\n"
            + "package io.netty.example.time;\n"
            + "\n"
            + "public class TimeDecoder extends ByteToMessageDecoder { // (1)\n"
            + "    @Override\n"
            + "    protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) { // (2)\n"
            + "        if (in.readableBytes() < 4) {\n"
            + "            return; // (3)\n"
            + "        }\n"
            + "\n"
            + "        out.add(in.readBytes(4)); // (4)\n"
            + "    }\n"
            + "}\n"
            + "ByteToMessageDecoder is an implementation of ChannelHandler which makes it easy to deal with the fragmentation issue.\n"
            + "ByteToMessageDecoder calls the decode() method with an internally maintained cumulative buffer whenever new data is received.\n"
            + "decode() can decide to add nothing to out where there is not enough data in the cumulative buffer. ByteToMessageDecoder will call decode() again when there is more data received.\n"
            + "If decode() adds an object to out, it means the decoder decoded a message successfully. ByteToMessageDecoder will discard the read part of the cumulative buffer. Please remember that you don't need to decode multiple messages. ByteToMessageDecoder will keep calling the decode() method until it adds nothing to out.\n"
            + "Now that we have another handler to insert into the ChannelPipeline, we should modify the ChannelInitializer implementation in the TimeClient:\n"
            + "\n"
            + "b.handler(new ChannelInitializer<SocketChannel>() {\n"
            + "    @Override\n"
            + "    public void initChannel(SocketChannel ch) throws Exception {\n"
            + "        ch.pipeline().addLast(new TimeDecoder(), new TimeClientHandler());\n"
            + "    }\n"
            + "});\n"
            + "If you are an adventurous person, you might want to try the ReplayingDecoder which simplifies the decoder even more. You will need to consult the API reference for more information though.\n"
            + "\n"
            + "public class TimeDecoder extends ReplayingDecoder<Void> {\n"
            + "    @Override\n"
            + "    protected void decode(\n"
            + "            ChannelHandlerContext ctx, ByteBuf in, List<Object> out) {\n"
            + "        out.add(in.readBytes(4));\n"
            + "    }\n"
            + "}\n"
            + "Additionally, Netty provides out-of-the-box decoders which enables you to implement most protocols very easily and helps you avoid from ending up with a monolithic unmaintainable handler implementation. Please refer to the following packages for more detailed examples:\n"
            + "\n"
            + "io.netty.example.factorial for a binary protocol, and\n"
            + "io.netty.example.telnet for a text line-based protocol.\n"
            + "Speaking in POJO instead of ByteBuf\n"
            + "All the examples we have reviewed so far used a ByteBuf as a primary data structure of a protocol message. In this section, we will improve the TIME protocol client and server example to use a POJO instead of a ByteBuf.\n"
            + "\n"
            + "The advantage of using a POJO in your ChannelHandlers is obvious; your handler becomes more maintainable and reusable by separating the code which extracts information from ByteBuf out from the handler. In the TIME client and server examples, we read only one 32-bit integer and it is not a major issue to use ByteBuf directly. However, you will find it is necessary to make the separation as you implement a real world protocol.\n"
            + "\n"
            + "First, let us define a new type called UnixTime.\n"
            + "\n"
            + "package io.netty.example.time;\n"
            + "\n"
            + "import java.util.Date;\n"
            + "\n"
            + "public class UnixTime {\n"
            + "\n"
            + "    private final long value;\n"
            + "\n"
            + "    public UnixTime() {\n"
            + "        this(System.currentTimeMillis() / 1000L + 2208988800L);\n"
            + "    }\n"
            + "\n"
            + "    public UnixTime(long value) {\n"
            + "        this.value = value;\n"
            + "    }\n"
            + "\n"
            + "    public long value() {\n"
            + "        return value;\n"
            + "    }\n"
            + "\n"
            + "    @Override\n"
            + "    public String toString() {\n"
            + "        return new Date((value() - 2208988800L) * 1000L).toString();\n"
            + "    }\n"
            + "}\n"
            + "We can now revise the TimeDecoder to produce a UnixTime instead of a ByteBuf.\n"
            + "\n"
            + "@Override\n"
            + "protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) {\n"
            + "    if (in.readableBytes() < 4) {\n"
            + "        return;\n"
            + "    }\n"
            + "\n"
            + "    out.add(new UnixTime(in.readUnsignedInt()));\n"
            + "}\n"
            + "With the updated decoder, the TimeClientHandler does not use ByteBuf anymore:\n"
            + "\n"
            + "@Override\n"
            + "public void channelRead(ChannelHandlerContext ctx, Object msg) {\n"
            + "    UnixTime m = (UnixTime) msg;\n"
            + "    System.out.println(m);\n"
            + "    ctx.close();\n"
            + "}\n"
            + "Much simpler and elegant, right? The same technique can be applied on the server side. Let us update the TimeServerHandler first this time:\n"
            + "\n"
            + "@Override\n"
            + "public void channelActive(ChannelHandlerContext ctx) {\n"
            + "    ChannelFuture f = ctx.writeAndFlush(new UnixTime());\n"
            + "    f.addListener(ChannelFutureListener.CLOSE);\n"
            + "}\n"
            + "Now, the only missing piece is an encoder, which is an implementation of ChannelHandler that translates a UnixTime back into a ByteBuf. It's much simpler than writing a decoder because there's no need to deal with packet fragmentation and assembly when encoding a message.\n"
            + "\n"
            + "package io.netty.example.time;\n"
            + "\n"
            + "public class TimeEncoder extends ChannelHandlerAdapter {\n"
            + "    @Override\n"
            + "    public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) {\n"
            + "        UnixTime m = (UnixTime) msg;\n"
            + "        ByteBuf encoded = ctx.alloc().buffer(4);\n"
            + "        encoded.writeInt((int) m.value());\n"
            + "        ctx.write(encoded, promise); // (1)\n"
            + "    }\n"
            + "}\n"
            + "There are a few important things to notice in this handler method:\n"
            + "\n"
            + "First, we pass the original ChannelPromise as-is so that Netty marks it as success or failure when the encoded data is actually written out to the wire.\n"
            + "\n"
            + "Second, we did not call ctx.flush(). There is a separate handler method void flush(ChannelHandlerContext ctx) which is purposed to override the flush() operation.\n"
            + "\n"
            + "To simplify even further, you can make use of MessageToByteEncoder:\n"
            + "\n"
            + "public class TimeEncoder extends MessageToByteEncoder<UnixTime> {\n"
            + "    @Override\n"
            + "    protected void encode(ChannelHandlerContext ctx, UnixTime msg, ByteBuf out) {\n"
            + "        out.writeInt((int) msg.value());\n"
            + "    }\n"
            + "}\n"
            + "The last task left is to insert a TimeEncoder into the ChannelPipeline on the server side before the TimeServerHandler, and it is left as a trivial exercise.\n"
            + "\n"
            + "Shutting Down Your Application\n"
            + "Shutting down a Netty application is usually as simple as shutting down all EventLoopGroups you created via shutdownGracefully(). It returns a Future that notifies you when the EventLoopGroup has been terminated completely and all Channels that belong to the group have been closed.\n"
            + "\n"
            + "Summary\n"
            + "In this chapter, we had a quick tour of Netty with a demonstration on how to write a fully working network application on top of Netty.\n"
            + "\n"
            + "There is more detailed information about Netty in the upcoming chapters. We also encourage you to review the Netty examples in the io.netty.example package.\n"
            + "\n"
            + "Please also note that the community is always waiting for your questions and ideas to help you and keep improving Netty and its documentation based on your feed back.\n"
            + "\n"
            + "Table of Contents\n"
            + "Preface\n"
            + "The Solution\n"
            + "Getting Started\n"
            + "Last retrieved on 02-Sep-2015";

    @Test
    public void testCount() throws Exception {
        WordCount wordCount = new WordCount();
        Map<String, Long> stringLongMap = wordCount.wordCount("hello world!", "");
        System.out.println(stringLongMap);
        Map<String, Long> expected = simpleWordCount("hello world!", "");
        Assert.assertEquals(expected, stringLongMap);
    }

    @Test
    public void testCount2() throws Exception {
        WordCount wordCount = new WordCount();
        Map<String, Long> count = wordCount.wordCount(WORDS, "");
        System.out.println(count);
        Map<String, Long> expected = simpleWordCount(WORDS, "");
        Assert.assertEquals(expected, count);
    }

    @Test
    public void testCount3() throws Exception {
        WordCount wordCount = new WordCount();
        Map<String, Long> count = wordCount.wordCount(WORDS, " ");
        System.out.println(count);
        Map<String, Long> expected = simpleWordCount(WORDS, " ");
        Assert.assertEquals(expected, count);
    }

    private Map<String, Long> simpleWordCount(String word, String delimiter) {
        String[] split = word.split(delimiter);
        Map<String, Long> map = new HashMap<>();
        for (String s : split) {
            map.put(s, map.getOrDefault(s, 0L) + 1L);
        }
        return map;
    }
}
